## makeCacheMatrix generates a list vector containing four functions.  Using 
## scoping rules, values can be shared between the four functions of the list.
## cacheSolve takes a vector generated by makeCacheMatrix, validates if the inverse
## has already been generated and either calls on the functions stored within the list
## vector to generate the inverse or displays the already stored inverse value.
## Functions based on makeVector() and cachemean() provided by in assignment descr

## Takes input of a matrix and outputs a list vector containing four functions.
## Scoping rules leveraged on values m and x within function.
## set() - allows for resetting matrix stored and flag for calc'ed inverse
## get() - returns inverse
## setinverse() - sets stored inverse value
## getinverse() - returns inverse value

makeCacheMatrix <- function(x = matrix()) {
      m <- NULL
      set <- function(y) {
            x <<- y
            m <<- NULL
      }
      get <- function() x
      setinverse <- function(inverse) m <<- inverse
      getinverse <- function() m
      list(set = set, get = get,
           setinverse = setinverse,
           getinverse = getinverse)
}


## Takes a provided vector and provides the inverses of that
## vector.  It first checks to see if the inverse as already 
## been calculated by calling getinverse() from within the 
## vector.  If a non null value is found, the inverse value
## is displayed.  Otherwise the inverse is calculated and 
## stored in the vector using setinverse().

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
      m <- x$getinverse()
      if(!is.null(m)) {
            message("getting cached data")
            return(m)
      }
      data <- x$get()
      m <- solve(data, ...)
      x$setinverse(m)
      m
}
